-- Sprint 1 — Documentação de chaves de configuração
-- Nenhuma migration estrutural necessária.
-- A tabela `settings` já suporta qualquer chave key-value por tenant.
-- Este arquivo serve como referência das chaves introduzidas neste sprint.
--
-- Para consultar as configs de um tenant:
-- SELECT key, value FROM settings WHERE tenant_id = '<id>' AND key LIKE 'pipeline_%';
--
-- Para inserir manualmente (se necessário para um tenant específico):
-- INSERT INTO settings (tenant_id, key, value) VALUES ('<id>', 'pipeline_fallback_enabled', 'false')
--   ON CONFLICT (tenant_id, key) DO NOTHING;
